// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9v4e0J_Ci3Fo5caO5eZsTYTDLTsSpbyI',
    appId: '1:589340273826:web:46875245ed7225677ffbfb',
    messagingSenderId: '589340273826',
    projectId: 'kampus-mobil-proje',
    authDomain: 'kampus-mobil-proje.firebaseapp.com',
    storageBucket: 'kampus-mobil-proje.firebasestorage.app',
    measurementId: 'G-77L77FNFZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZr3nUSJHxsGuVun16zsS0bg242QOv_EE',
    appId: '1:589340273826:android:cd3f41f1286569df7ffbfb',
    messagingSenderId: '589340273826',
    projectId: 'kampus-mobil-proje',
    storageBucket: 'kampus-mobil-proje.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDBPipqZ2qI6D1eyAqsmJo2xmQV8tjpeE',
    appId: '1:589340273826:ios:80ff17f7dad6154b7ffbfb',
    messagingSenderId: '589340273826',
    projectId: 'kampus-mobil-proje',
    storageBucket: 'kampus-mobil-proje.firebasestorage.app',
    iosBundleId: 'com.example.smartCampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDBPipqZ2qI6D1eyAqsmJo2xmQV8tjpeE',
    appId: '1:589340273826:ios:80ff17f7dad6154b7ffbfb',
    messagingSenderId: '589340273826',
    projectId: 'kampus-mobil-proje',
    storageBucket: 'kampus-mobil-proje.firebasestorage.app',
    iosBundleId: 'com.example.smartCampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9v4e0J_Ci3Fo5caO5eZsTYTDLTsSpbyI',
    appId: '1:589340273826:web:ef66c1455ef65e8c7ffbfb',
    messagingSenderId: '589340273826',
    projectId: 'kampus-mobil-proje',
    authDomain: 'kampus-mobil-proje.firebaseapp.com',
    storageBucket: 'kampus-mobil-proje.firebasestorage.app',
    measurementId: 'G-SBDKQPFSN0',
  );
}
